version: '3'
services:
  app:
    container_name: laravel_php
    build: ./docker/php
    depends_on:
      - mysql 
    volumes:
      - ./document_root:/var/www/html

  web:
    container_name: laravel_nginx
    image: nginx
    ports:
      - '8000:80'
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/ngix/conf.d/default.conf
      - ./document_root:/var/www/html

  mysql:
    container_name: laravel_db
    image: mysql:5.7
    ports:
      - '3333:3306'
    environment:
     MYSQL_DATABASE: laravel_db
     MYSQL_USER: user
     MYSQL_PASSWORD: password
     MYSQL_ROOT_PASSWORD: password
    command: --disable-partition-engine-check
    volumes:
      - mysql-data:/var/lib/mysql

    
volumes:
    mysql-data:
